version: "3"
services:
  node-app:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: 

